repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
